using HarmonyLib;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.Text;
using TMPro;
using System.Linq;
using UnityEngine;

namespace Shapez2UILib
{
    public static class StaticResources
    {
        public static readonly FieldInfo componentChildComponentReferences = AccessTools.Field(typeof(HUDComponent), "ChildComponentReferences");
        public static readonly MethodInfo componentAddChildViewInternal = AccessTools.Method(typeof(HUDComponent), "AddChildViewInternal");
        public static readonly FieldInfo componentDependencyResolver = AccessTools.Field(typeof(HUDComponent), "DependencyResolver");
        public static readonly Sprite HUDButtonBase = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDButtonBase");
        public static readonly Sprite HUDSecondaryButtonBase = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDSecondaryButtonBase");
        public static readonly Sprite HUDButtonHover = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDButtonHover");
        public static readonly Sprite HUDPrimaryLightPanelMask = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDPrimaryLightPanelMask");
        public static readonly Sprite HUDPrimaryLightPanel = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDPrimaryLightPanel");
        public static readonly Sprite HUDSecondaryPanel = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDSecondaryPanel");
        public static readonly Sprite HUDScrollbarPanelBg = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDScrollbarPanelBg");
        public static readonly Sprite HUDAntiAliasedHorizontalScrollDivider = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDAntiAliasedHorizontalScrollDivider");
        public static readonly Sprite HUDAntiAliasedHorizontalDivider = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDAntiAliasedHorizontalDivider");
        public static readonly Sprite HUDIconButtonBase = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDIconButtonBase");
        public static readonly Sprite HUDIconButtonHover = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDIconButtonHover");
        public static readonly Sprite HUDIconButtonActive = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDIconButtonActive");
        public static readonly Sprite HUDPanelHighlightFG = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDPanelHighlightFG");
        public static readonly Sprite HUDIconButtonHighlight = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDIconButtonHighlight");
        public static readonly Sprite HUDSoloBadge = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDSoloBadge");
        public static readonly Sprite HUDPanelButtonBase = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDPanelButtonBase");
        public static readonly Sprite HUDTooltipArrowClean = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDTooltipArrowClean");
        public static readonly Sprite DropdownDownIndicator = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "DropdownDownIndicator");
        public static readonly Sprite HUDSliderTrackPattern = Resources.FindObjectsOfTypeAll<Sprite>().First(t => t.name == "HUDSliderTrackPattern");
        public static readonly Material DefaultTranslucent = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "Default-Translucent");
        public static readonly Material UIAnimatedPanelMenuMaterial = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-AnimatedPanelMenuMaterial");
        public static readonly Material UISpriteWithMipMapBiasOverride = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-SpriteWithMipMapBiasOverride");
        public static readonly Material UIAnimatedButtonMaterial = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-AnimatedButtonMaterial");
        public static readonly Material UIAnimatedButtonBaseMaterial = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-AnimatedButtonBaseMaterial");
        public static readonly Material UIAnimatedIconMaterial = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-AnimatedIconMaterial");
        public static readonly Material UIAnimatedIconButtonMaterial = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-AnimatedIconButtonMaterial");
        public static readonly Material UIAnimatedHighlightMaterial = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-AnimatedHighlightMaterial");
        public static readonly Material UIAnimatedSecondaryPanelMaterial = Resources.FindObjectsOfTypeAll<Material>().First(m => m.name == "UI-AnimatedSecondaryPanelMaterial");
        public static readonly TMP_FontAsset FontMediumSDF = Resources.FindObjectsOfTypeAll<TMP_FontAsset>().First(m => m.name == "Font-Medium SDF");
        public static readonly TMP_FontAsset FontLightSDF = Resources.FindObjectsOfTypeAll<TMP_FontAsset>().First(m => m.name == "Font-Light SDF");
        public static readonly FieldInfo HUDInputFieldUIInputFieldInfo = AccessTools.Field(typeof(HUDInputField), "UIInputField");
        public static readonly FieldInfo HUDInputFieldUIPlaceholderTextInfo = AccessTools.Field(typeof(HUDInputField), "UIPlaceholderText");
        public static readonly FieldInfo HUDScrollContainerUIScrollRectInfo = AccessTools.Field(typeof(HUDScrollContainer), "UIScrollRect");
        public static readonly FieldInfo HUDLocalizedTextUITextInfo = AccessTools.Field(typeof(HUDLocalizedText), "UIText");
        public static readonly FieldInfo HUDButtonUITextInfo = AccessTools.Field(typeof(HUDButton), "UIText");
        public static readonly FieldInfo HUDButtonUIButtonInfo = AccessTools.Field(typeof(HUDButton), "UIButton");
        public static readonly FieldInfo HUDButtonUIMainGroupInfo = AccessTools.Field(typeof(HUDButton), "UIMainGroup");
        public static readonly FieldInfo HUDButtonUIHoverIndicatorGroupInfo = AccessTools.Field(typeof(HUDButton), "UIHoverIndicatorGroup");
        public static readonly FieldInfo HUDButtonUIMainTransformInfo = AccessTools.Field(typeof(HUDButton), "UIMainTransform");
        public static readonly FieldInfo HUDAnimatedRoundButtonUIButtonInfo = AccessTools.Field(typeof(HUDAnimatedRoundButton), "UIButton");
        public static readonly FieldInfo HUDAnimatedRoundButtonUIIconSpriteInfo = AccessTools.Field(typeof(HUDAnimatedRoundButton), "UIIconSprite");
        public static readonly FieldInfo HUDAnimatedRoundButtonUIIconTransformInfo = AccessTools.Field(typeof(HUDAnimatedRoundButton), "UIIconTransform");
        public static readonly FieldInfo HUDAnimatedRoundButtonUIMainIconInfo = AccessTools.Field(typeof(HUDAnimatedRoundButton), "UIMainIcon");
        public static readonly FieldInfo tmpInputFieldRegexValue = AccessTools.Field(typeof(TMP_InputField), "m_RegexValue");
        public static readonly MethodInfo addMenuButtonMethod = AccessTools.Method(typeof(HUDMenuMainState), "AddMenuButton");
        public static readonly MethodInfo IMainMenuStateControlSwitchToStateInfo = AccessTools.Method(typeof(IMainMenuStateControl), nameof(IMainMenuStateControl.SwitchToState));
        public static readonly FieldInfo HUDMenuBackButton_TextIdInfo = AccessTools.Field(typeof(HUDMenuBackButton), "_TextId");
        public static readonly FieldInfo HUDComponentChildren = AccessTools.Field(typeof(HUDComponent), "Children");
        public static readonly FieldInfo HUDComponentLoadedChildren = AccessTools.Field(typeof(HUDComponent), "LoadedChildren");
        public static readonly FieldInfo HUDIconButtonUIActiveGroup = AccessTools.Field(typeof(HUDIconButton), "UIActiveGroup");
        public static readonly FieldInfo HUDIconButtonUIBadge = AccessTools.Field(typeof(HUDIconButton), "UIBadge");
        public static readonly FieldInfo HUDIconButtonUIButton = AccessTools.Field(typeof(HUDIconButton), "UIButton");
        public static readonly FieldInfo HUDIconButtonUIHighlightGroup = AccessTools.Field(typeof(HUDIconButton), "UIHighlightGroup");
        public static readonly FieldInfo HUDIconButtonUIHoverIndicatorGroup = AccessTools.Field(typeof(HUDIconButton), "UIHoverIndicatorGroup");
        public static readonly FieldInfo HUDIconButtonUIIcon = AccessTools.Field(typeof(HUDIconButton), "UIIcon");
        public static readonly FieldInfo HUDIconButtonUIMainGroup = AccessTools.Field(typeof(HUDIconButton), "UIMainGroup");
        public static readonly FieldInfo HUDIconButtonUIMainTransform = AccessTools.Field(typeof(HUDIconButton), "UIMainTransform");
        public static readonly FieldInfo HUDIconButtonUITooltipTarget = AccessTools.Field(typeof(HUDIconButton), "UITooltipTarget");
        public static readonly FieldInfo HUDIconButton_TooltipAlignment = AccessTools.Field(typeof(HUDIconButton), "_TooltipAlignment");
        public static readonly FieldInfo HUDIconButton_TooltipKeybinding = AccessTools.Field(typeof(HUDIconButton), "_TooltipKeybinding");
        public static readonly FieldInfo HUDIconButton_Icon = AccessTools.Field(typeof(HUDIconButton), "_Icon");
        public static readonly FieldInfo HUDIconButton_HasTooltip = AccessTools.Field(typeof(HUDIconButton), "_HasTooltip");
        public static readonly FieldInfo HUDBadgeUIBadgeTransform = AccessTools.Field(typeof(HUDBadge), "UIBadgeTransform");
        public static readonly FieldInfo HUDToggleControlUIButton = AccessTools.Field(typeof(HUDToggleControl), "UIButton");
        public static readonly FieldInfo HUDToggleControlUIKnobTransform = AccessTools.Field(typeof(HUDToggleControl), "UIKnobTransform");
        public static readonly FieldInfo HUDToggleControlUIMainGroup = AccessTools.Field(typeof(HUDToggleControl), "UIMainGroup");
        public static readonly FieldInfo HUDToggleControlUIOffIndicator = AccessTools.Field(typeof(HUDToggleControl), "UIOffIndicator");
        public static readonly FieldInfo HUDToggleControlUIOnIndicator = AccessTools.Field(typeof(HUDToggleControl), "UIOnIndicator");
        public static readonly FieldInfo HUDDropdownControlUIDropdown = AccessTools.Field(typeof(HUDDropdownControl), "UIDropdown");
        public static readonly FieldInfo HUDDropdownControlUIMainGroup = AccessTools.Field(typeof(HUDDropdownControl), "UIMainGroup");
        public static readonly FieldInfo HUDDropdownControlUIValueText = AccessTools.Field(typeof(HUDDropdownControl), "UIValueText");
        public static readonly FieldInfo HUDEnumSelectorControlUIDropdown = AccessTools.Field(typeof(HUDEnumSelectorControl), "UIDropdown");
        public static readonly FieldInfo HUDSliderControlUISlider = AccessTools.Field(typeof(HUDSliderControl), "UISlider");
        public static readonly FieldInfo HUDSliderControlUIValueText = AccessTools.Field(typeof(HUDSliderControl), "UIValueText");
        public static readonly FieldInfo HUDDialogUIReferencesInfo = AccessTools.Field(typeof(HUDDialog), "UIReferences");
        public static readonly FieldInfo HUDLocalizedText_TranslationInfo = AccessTools.Field(typeof(HUDLocalizedText), "_Translation");
    }
}
